server:
  port: 9001
spring:
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: running-location-service
  datasource:
    url: jdbc:mysql://localhost:3306/private
    username: root
    password: vagrant
    driver-class-name: com.mysql.jdbc.Driver
